// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ZO7ZONp-Bcnb10CBnRzLk-37XJPrLpY',
    appId: '1:810802741352:web:e28291d199f5125c3b3bdd',
    messagingSenderId: '810802741352',
    projectId: 'flutter-full-news-app-11ee8',
    authDomain: 'flutter-full-news-app-11ee8.firebaseapp.com',
    storageBucket: 'flutter-full-news-app-11ee8.appspot.com',
    measurementId: 'G-3S8Q6DEDCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg4Wo2WcINVIDIFoAdIhpQXHdrudtLXhU',
    appId: '1:810802741352:android:d5afcaa5d5b440523b3bdd',
    messagingSenderId: '810802741352',
    projectId: 'flutter-full-news-app-11ee8',
    storageBucket: 'flutter-full-news-app-11ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjYyohGM84nA0ImXD-e14lumHXwK_ZQbU',
    appId: '1:810802741352:ios:ae370e4bb9446ac93b3bdd',
    messagingSenderId: '810802741352',
    projectId: 'flutter-full-news-app-11ee8',
    storageBucket: 'flutter-full-news-app-11ee8.appspot.com',
    iosBundleId: 'com.example.riverpodProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjYyohGM84nA0ImXD-e14lumHXwK_ZQbU',
    appId: '1:810802741352:ios:e589d2e721e1edfa3b3bdd',
    messagingSenderId: '810802741352',
    projectId: 'flutter-full-news-app-11ee8',
    storageBucket: 'flutter-full-news-app-11ee8.appspot.com',
    iosBundleId: 'com.example.riverpodProject.RunnerTests',
  );
}
